# Generated by Django 4.2.1 on 2023-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="no_picture.png", upload_to="recipes"),
        ),
    ]
